=== tomsku1/JAVA-JSON/XSD i XML/uniwersytet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="uniwersytet">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="wydzial" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="wydzial">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nazwa" type="xs:string"/>
				<xs:element ref="adres" maxOccurs="unbounded"/>
				<xs:element ref="pracownik" maxOccurs="unbounded"/>
				<xs:element ref="przedmiot" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="ID_wydzialu" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="adres">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ulica" type="xs:string"/>
				<xs:element name="numer" type="xs:string"/>
				<xs:element name="kod_pocztowy" type="xs:string"/>
				<xs:element name="miejscowosc" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="pracownik">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="imie" type="xs:string"/>
				<xs:element name="nazwisko" type="xs:string"/>
				<xs:element name="tytul" type="xs:string" minOccurs="0"/>
				<xs:element name="kategoria">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="naukowy"/>
							<xs:enumeration value="administracyjny"/>
							<xs:enumeration value="techniczny"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="adres" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="ID_pracownika" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="przedmiot">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nazwa" type="xs:string"/>
				<xs:element name="liczba_uczestnikow">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="6"/>
							<xs:maxInclusive value="400"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="ID_przedmiotu" type="xs:ID" use="required"/>
			<xs:attribute name="ID_wykladowcy"  type="xs:IDREFS" use="required"/>
		</xs:complexType>
	</xs:element>

	
</xs:schema>

=== tomsku1/JAVA-JSON/XSD i XML/uniwersytet.xml
<?xml version="1.0" encoding="UTF-8"?>
<uniwersytet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="uniwersytet.xsd">
		  <wydzial ID_wydzialu="W1">
			<nazwa>informatyczny</nazwa>
			<adres>
				<ulica>Marszalkowska</ulica>
				<numer>3</numer>
				<kod_pocztowy>02-400</kod_pocztowy>
				<miejscowosc>Warszawa</miejscowosc>
			</adres>
			<pracownik ID_pracownika="P1">
				<imie>Jacek</imie>
				<nazwisko>Kowalski</nazwisko>
				<kategoria>techniczny</kategoria>
				<adres>
					<ulica>Piekna</ulica>
					<numer>12</numer>
					<kod_pocztowy>53-500</kod_pocztowy>
					<miejscowosc>Wroclaw</miejscowosc>
				</adres>
			</pracownik>
			<pracownik ID_pracownika="P2">
				<imie>Grazyna</imie>
				<nazwisko>Nowak</nazwisko>
				<kategoria>administracyjny</kategoria>
				<adres>
					<ulica>Slaska</ulica>
					<numer>46C</numer>
					<kod_pocztowy>57-500</kod_pocztowy>
					<miejscowosc>Wroclaw</miejscowosc>
				</adres>
			</pracownik>
			<pracownik ID_pracownika="P3">
				<imie>Jerzy</imie>
				<nazwisko>Piatek</nazwisko>
				<kategoria>naukowy</kategoria>
				<adres>
					<ulica>Sliczna</ulica>
					<numer>1</numer>
					<kod_pocztowy>53-540</kod_pocztowy>
					<miejscowosc>Wroclaw</miejscowosc>
				</adres>
			</pracownik>
			<przedmiot ID_przedmiotu="PRZ1" ID_wykladowcy="P1">
				<nazwa>matematyka</nazwa>
				<liczba_uczestnikow>280</liczba_uczestnikow>
			</przedmiot>
			<przedmiot ID_przedmiotu="PRZ2" ID_wykladowcy="P2">
				<nazwa>informatyka</nazwa>
				<liczba_uczestnikow>350</liczba_uczestnikow>
			</przedmiot>
		  </wydzial>
		  
		  <wydzial ID_wydzialu="W2">
			<nazwa>dziennikarstwa</nazwa>
			<adres>
				<ulica>Dluga</ulica>
				<numer>6A</numer>
				<kod_pocztowy>50-500</kod_pocztowy>
				<miejscowosc>Wroclaw</miejscowosc>
			</adres>
			<pracownik ID_pracownika="P4">
				<imie>Stanislaw</imie>
				<nazwisko>Zuk</nazwisko>
				<kategoria>naukowy</kategoria>
				<adres>
					<ulica>Maczka</ulica>
					<numer>4</numer>
					<kod_pocztowy>56-540</kod_pocztowy>
					<miejscowosc>Wroclaw</miejscowosc>
				</adres>
			</pracownik>
			<przedmiot ID_przedmiotu="PRZ3" ID_wykladowcy="P4">
				<nazwa>JAVA and JSON</nazwa>
				<liczba_uczestnikow>399</liczba_uczestnikow>
			</przedmiot>
		  </wydzial>		
</uniwersytet>
